services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: sh -c "python manage.py migrate &&
                    gunicorn core.wsgi:application --bind 0.0.0.0:8000" 
    volumes: 
      - static_volume:/home/app/code/static
    env_file: 
      - .env
    image: web
    restart: "unless-stopped"
  
  django-q:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: python manage.py qcluster
    volumes: 
      - static_volume:/home/app/code/static
    depends_on:
      - web
    restart: "unless-stopped"
  
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: 
    - 80:80 
    volumes:  
      - static_volume:/home/app/code/static 
    depends_on:
      - web 

volumes:
  static_volume:
